### ISSUE TITLE
small tweaks

### ISSUE THREAD

**Issue by FrankReh** [dicej/isyswasfa#2]
What a nice contribution I stumbled on with this crate. Thank you for making it so straight forward for a newcomer to follow.

There were a few tweaks to the build and run instructions I had to figure out.

`git submodule init` and `git submodule update` were needed.

I had to switch back to the prior rustc version with `rustup override set 1.76.0`. 1.77 must introduce some new warnings that are being treated as fatal errors.

And I had to replace `debug` with `release` in
`wasm-tools component new --adapt wasi_snapshot_preview1.reactor.wasm test/rust-cases/target/wasm32-wasi/debug/hash_all.wasm -o hash-all.wasm`.

After that, the server could be run and the curl command worked!

And overall, this helped me understand what is meant by the composability problem with WASI 0.2. I'm sure it will help others too. If I try to  paraphrase: the WASI team wants to allow guests to use async Components so the async runtime doesn't have to be built into the guest itself. This makes the WASM modules even more light weight and flexible.

**Comment by dicej** [comment]
Thanks for the feedback, @FrankReh!  I believe I've addressed everything in https://github.com/dicej/isyswasfa/commit/df9a153fafbbdf532d811bdc53e61ff7368e4898

> If I try to paraphrase: the WASI team wants to allow guests to use async Components so the async runtime doesn't have to be built into the guest itself. This makes the WASM modules even more light weight and flexible.

Yes, that's a good paraphrase.  The other aspect is that since the host is providing the async runtime, it can be shared among several components which have been composed using e.g. `wasm-compose` or `wac`, which isn't possible if each component tries to bundle its own async runtime and use `wasi:io/poll@0.2.0` independently.
